<?php
/**
 * URL builder/converter for language-prefixed links.
 *
 * @package TranslatePlus
 */

if (! defined('ABSPATH')) {
    exit;
}

final class TranslatePlus_URL_Builder {

    /**
     * Canonical default language code used in URL decisions.
     */
    public static function get_default_language_code(): string {
        $code = apply_filters('translateplus_permalink_default_language', TranslatePlus_API::DEFAULT_SOURCE);

        return is_string($code) && $code !== ''
            ? ( TranslatePlus_Languages::normalize($code) ?? TranslatePlus_API::DEFAULT_SOURCE )
            : TranslatePlus_API::DEFAULT_SOURCE;
    }

    /**
     * Whether default language URLs should include a language prefix.
     */
    public static function should_prefix_default_language(): bool {
        if (class_exists('TranslatePlus_Settings', false)) {
            return \TranslatePlus_Settings::is_default_language_prefixed();
        }

        return (bool) apply_filters('translateplus_permalink_prefix_default_language', false);
    }

    /**
     * Convert any site URL to a language-prefixed URL when needed.
     *
     * @param string $url  Absolute URL.
     * @param string $lang Language code.
     */
    public static function convert_url(string $url, string $lang): string {
        $url = self::normalize_to_site_absolute_url($url);
        if ($url === '') {
            return $url;
        }

        $lang = TranslatePlus_Languages::normalize($lang);
        if ($lang === null || $lang === '' || $lang === 'auto') {
            return $url;
        }

        $default = self::get_default_language_code();
        if ($lang === $default && ! self::should_prefix_default_language()) {
            return self::remove_language_from_url($url, $lang);
        }

        return self::insert_language_after_home_path($url, $lang);
    }

    /**
     * Build a localized permalink from a post object + base permalink.
     *
     * @param string  $permalink Base permalink generated by WordPress.
     * @param WP_Post $post      Post object.
     */
    public static function build_permalink_for_post(string $permalink, WP_Post $post): string {
        if (! in_array($post->post_type, TranslatePlus_Settings::get_translatable_post_types(), true)) {
            return $permalink;
        }

        $request_lang = self::detect_request_language();
        if (
            $request_lang !== ''
            && self::should_force_request_language_for_post($post)
            && class_exists('TranslatePlus_Translation_Group', false)
        ) {
            $group = get_post_meta((int) $post->ID, TranslatePlus_Translation_Group::META_GROUP, true);
            if (is_string($group) && $group !== '') {
                $translated_id = TranslatePlus_Translation_Group::find_post_in_group_by_language($group, $request_lang, $post->post_type);
                if ($translated_id > 0 && $translated_id !== (int) $post->ID) {
                    $translated = get_post($translated_id);
                    if ($translated instanceof WP_Post && $translated->post_status === 'publish') {
                        $translated_permalink = get_permalink($translated);
                        if (is_string($translated_permalink) && $translated_permalink !== '') {
                            return self::convert_url($translated_permalink, $request_lang);
                        }
                    }
                }
            }
        }

        $stored = TranslatePlus_Translation_Group::get_post_language($post->ID);
        $lang   = TranslatePlus_Languages::normalize($stored);
        if ($lang === null || $lang === 'auto') {
            $lang = self::get_default_language_code();
        }

        return self::convert_url($permalink, $lang);
    }

    /**
     * Apply request-language sibling remap only for the currently queried singular post.
     * Prevents cross-language double-prefix URLs in switchers/menu lists.
     */
    private static function should_force_request_language_for_post(WP_Post $post): bool {
        if (! is_singular()) {
            return false;
        }

        $queried_id = get_queried_object_id();

        return $queried_id > 0 && $queried_id === (int) $post->ID;
    }

    /**
     * Detect active frontend language from query var or current request path.
     */
    private static function detect_request_language(): string {
        if (is_admin() || wp_doing_ajax() || (defined('REST_REQUEST') && REST_REQUEST)) {
            return '';
        }

        if (class_exists('TranslatePlus_Rewrites', false)) {
            $q = get_query_var(TranslatePlus_Rewrites::QUERY_VAR_LANG, '');
            if (is_string($q) && $q !== '') {
                $n = TranslatePlus_Languages::normalize($q);
                if ($n !== null && $n !== 'auto') {
                    return $n;
                }
            }
        }

        // phpcs:ignore WordPress.Security.NonceVerification.Recommended -- Read-only request path inspection.
        $uri = isset($_SERVER['REQUEST_URI']) ? (string) wp_unslash($_SERVER['REQUEST_URI']) : '';
        if ($uri === '') {
            return '';
        }

        $path = (string) wp_parse_url($uri, PHP_URL_PATH);
        $parts = array_values(array_filter(explode('/', trim($path, '/')), static function ($v) {
            return is_string($v) && $v !== '';
        }));
        if (empty($parts[0])) {
            return '';
        }

        $n = TranslatePlus_Languages::normalize((string) $parts[0]);

        return ($n !== null && $n !== 'auto') ? $n : '';
    }

    /**
     * Insert /{lang}/ after the home path (subdirectory installs supported).
     */
    private static function insert_language_after_home_path(string $url, string $lang): string {
        $parts = wp_parse_url($url);
        if (! is_array($parts) || empty($parts['host'])) {
            return $url;
        }

        $home      = wp_parse_url(home_url());
        $home_path = isset($home['path']) ? trim((string) $home['path'], '/') : '';
        $link_path = isset($parts['path']) ? (string) $parts['path'] : '/';
        $had_trailing = ( substr($link_path, -1) === '/' );
        $link_trim    = trim($link_path, '/');

        if ($home_path !== '' && strpos($link_trim . '/', $home_path . '/') === 0) {
            $rest = substr($link_trim, strlen($home_path) + 1);
        } elseif ($home_path === '') {
            $rest = $link_trim;
        } else {
            return $url;
        }

        if ($rest !== '' && preg_match('/^' . preg_quote($lang, '/') . '(\/|$)/', $rest)) {
            return $url;
        }

        $prefix   = $home_path !== '' ? $home_path . '/' : '';
        $new_path = '/' . $prefix . $lang . '/' . $rest;
        $new_path = str_replace('//', '/', $new_path);
        $new_path = $had_trailing ? trailingslashit($new_path) : untrailingslashit($new_path);

        return self::assemble_url($parts, $new_path);
    }

    /**
     * Remove the language segment right after home path.
     */
    private static function remove_language_from_url(string $url, string $lang): string {
        $parts = wp_parse_url($url);
        if (! is_array($parts) || empty($parts['host'])) {
            return $url;
        }

        $home      = wp_parse_url(home_url());
        $home_path = isset($home['path']) ? trim((string) $home['path'], '/') : '';
        $link_path = isset($parts['path']) ? (string) $parts['path'] : '/';
        $had_trailing = ( substr($link_path, -1) === '/' );
        $link_trim    = trim($link_path, '/');

        if ($home_path !== '' && strpos($link_trim . '/', $home_path . '/') === 0) {
            $rest = substr($link_trim, strlen($home_path) + 1);
            $prefix = $home_path . '/';
        } elseif ($home_path === '') {
            $rest = $link_trim;
            $prefix = '';
        } else {
            return $url;
        }

        if (! preg_match('/^' . preg_quote($lang, '/') . '(\/|$)/', $rest)) {
            return $url;
        }

        $rest = preg_replace('/^' . preg_quote($lang, '/') . '(\/)?/', '', $rest) ?? $rest;
        $new_path = '/' . $prefix . $rest;
        $new_path = str_replace('//', '/', $new_path);
        $new_path = $had_trailing ? trailingslashit($new_path) : untrailingslashit($new_path);

        return self::assemble_url($parts, $new_path);
    }

    /**
     * Ensure URL has site host/scheme so prefix logic cannot output malformed values.
     */
    private static function normalize_to_site_absolute_url(string $url): string {
        $url = trim($url);
        if ($url === '') {
            return '';
        }

        $parts = wp_parse_url($url);
        if (is_array($parts) && ! empty($parts['host'])) {
            return $url;
        }

        if (strpos($url, '?') === 0) {
            return home_url('/' . $url);
        }

        if ($url[0] !== '/') {
            $url = '/' . $url;
        }

        return home_url($url);
    }

    /**
     * @param array<string, mixed> $parts Parsed URL parts from wp_parse_url().
     */
    private static function assemble_url(array $parts, string $path): string {
        $scheme   = isset($parts['scheme']) ? $parts['scheme'] . '://' : '';
        $host     = isset($parts['host']) ? (string) $parts['host'] : '';
        $port     = isset($parts['port']) ? ':' . (int) $parts['port'] : '';
        $query    = isset($parts['query']) ? '?' . (string) $parts['query'] : '';
        $fragment = isset($parts['fragment']) ? '#' . (string) $parts['fragment'] : '';

        return $scheme . $host . $port . $path . $query . $fragment;
    }
}
